language: php

sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  composer install

script:
  phpunit --bootstrap=vendor/autoload.php --coverage-text --whitelist=src/Asserts src/Tests

notifications:
  email: false
