language: php

sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  composer install
  wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  chmod +x coveralls.phar

script:
  phpunit --bootstrap=vendor/autoload.php --coverage-clover clover.xml --coverage-text --whitelist=src/Asserts src/Tests

after_success:
  - travis_retry php coveralls.phar --verbose --coverage_clover=clover.xml

notifications:
  email: false
